-- CreateTable
CREATE TABLE "RawPassing" (
    "id" INTEGER NOT NULL,
    "pid" INTEGER NOT NULL,
    "timingPoint" TEXT NOT NULL,
    "result" INTEGER NOT NULL,
    "time" DOUBLE PRECISION NOT NULL,
    "invalid" BOOLEAN NOT NULL,
    "bib" INTEGER NOT NULL,
    "transponder" TEXT NOT NULL,
    "hits" INTEGER NOT NULL,
    "rssi" INTEGER NOT NULL,
    "battery" INTEGER NOT NULL,
    "temperature" INTEGER NOT NULL,
    "wuc" INTEGER NOT NULL,
    "loopId" INTEGER NOT NULL,
    "channel" INTEGER NOT NULL,
    "internalData" TEXT NOT NULL,
    "statusFlags" INTEGER NOT NULL,
    "deviceId" TEXT NOT NULL,
    "deviceName" TEXT NOT NULL,
    "orderId" INTEGER NOT NULL,
    "port" INTEGER NOT NULL,
    "isMarker" BOOLEAN NOT NULL,
    "fileNo" INTEGER NOT NULL,
    "passingNo" INTEGER NOT NULL,
    "customer" INTEGER NOT NULL,
    "received" TIMESTAMP(3) NOT NULL,
    "utcTime" TIMESTAMP(3) NOT NULL,
    "latitude" DOUBLE PRECISION NOT NULL,
    "longitude" DOUBLE PRECISION NOT NULL,
    "altitude" DOUBLE PRECISION NOT NULL,
    "flag" TEXT NOT NULL,

    CONSTRAINT "RawPassing_pkey" PRIMARY KEY ("id")
);
